logging:
  level.: DEBUG

spring:
  http:
    multipart:
      location: ${java.io.tmpdir}
      max-file-size: 50Mb
      max-request-size: 50Mb

com:
  justgifit:
    gif-location: ${java.io.tmpdir}/gif/
    create-result-dir: true

greeting: Generic Hello
