logging:
  level.: INFO

spring:
  http:
    multipart:
      location: ${java.io.tmpdir}/gif/upload2
      max-file-size: 50Mb
      max-request-size: 50Mb

com:
  justgifit:
    export-location: ${java.io.tmpdir}/gif/export2
    create-result-dir: true

